export const mockArticles = [
  {
    id: 1,
    title: "AI Breakthrough: New Neural Network Architecture Reduces Training Time by 50%",
    summary: "Researchers have published a new paper detailing a novel neural network architecture that significantly speeds up training without sacrificing accuracy.",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=600",
    category: "Technology",
    source: "TechDaily",
    date: "2026-03-20T10:00:00Z",
    sentiment: "Positive",
  },
  {
    id: 2,
    title: "Global Markets See Slight Dip Amidst Caution Over Interest Rates",
    summary: "Stock markets worldwide experienced a minor pullback today as investors remained cautious ahead of the central bank's upcoming decision on interest rates.",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a2236b0?auto=format&fit=crop&q=80&w=600",
    category: "Business",
    source: "Financial Times",
    date: "2026-03-19T14:30:00Z",
    sentiment: "Negative",
  },
  {
    id: 3,
    title: "Championship Finals Set: Underdogs Pull Off Major Upset in Semis",
    summary: "In a stunning turn of events, the unseeded local team has defeated the reigning champions to secure their spot in this weekend's grand final.",
    image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&q=80&w=600",
    category: "Sports",
    source: "Sports Network",
    date: "2026-03-21T08:15:00Z",
    sentiment: "Positive",
  },
  {
    id: 4,
    title: "Award-Winning Director Announces Next Sci-Fi Epic",
    summary: "The visionary director behind last year's biggest blockbuster has officially announced their next project, a sprawling sci-fi epic set to release in 2028.",
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=600",
    category: "Entertainment",
    source: "Hollywood Insider",
    date: "2026-03-18T16:45:00Z",
    sentiment: "Neutral",
  },
  {
    id: 5,
    title: "New Policy Bill Passed Aiming to Improve Sustainable Urban Infrastructure",
    summary: "The legislative assembly has passed a new bill allocating significant funds to upgrade city infrastructure with a focus on green energy and sustainability.",
    image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=600",
    category: "Politics",
    source: "Capitol News",
    date: "2026-03-20T09:20:00Z",
    sentiment: "Positive",
  },
  {
    id: 6,
    title: "Tech Giant Faces Antitrust Probe Over App Store Practices",
    summary: "Regulators have opened a formal antitrust investigation into the major tech company's app store fees and exclusionary developer policies.",
    image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=80&w=600",
    category: "Technology",
    source: "Tech Insiders",
    date: "2026-03-21T11:10:00Z",
    sentiment: "Negative",
  }
];
